//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fugam.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fugam.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [header]
        ///width=16
        ///height=16
        ///tilewidth=32
        ///tileheight=32
        ///orientation=orthogonal
        ///
        ///[tilesets]
        ///tileset=../Pictures/Zpa4ZvlsD101dtshjhhSJW6Ga0qa8o4mIiJLsGH0XX9A6Sr1r3Z4AtKbetcLkBSz_old_double.png,32,32,0,0
        ///
        ///[layer]
        ///type=Tilelaag 1
        ///data=
        ///1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
        ///1,1,1,26,27,35,28,29,35,119,37,1,1,1,1,1,
        ///1,1,1,105,106,89,89,89,89,89,56,1,1,1,1,1,
        ///1,1,1,124,89,154,89,89,89,89,75,32,101,102,103,1,
        ///1,1,1,105,89,154,154,61,108,89,50,51,120,121,122,1,
        ///1,1,1,83,84,60,84,146,148,89,89,89,89,157,5 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string level1 {
            get {
                return ResourceManager.GetString("level1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tileset {
            get {
                object obj = ResourceManager.GetObject("tileset", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
